package com.grimschitz.mankomania.client;

public enum GameState {
    //    KEEP SYNCHRONIZED WITH SERVER!!!
    HELLO, LOBBY_WAITING, LOBBY_READY, GAME_START, GAME_MOVE, GAME_WAIT, GAME_END, MINIGAME_CASINO, MINIGAME_RACE, MINIGAME_EXCHANGE, MINIGAME_AUCTION, INFO
}
